#!/usr/bin/env python3
# encoding: utf-8
# coding style: pep8
# ====================================================
#   Copyright (C)2020 All rights reserved.
#
#   Author        : Xin-Xin MA
#   Email         : xxmawhu@163.com
#   File Name     : genInit.py
#   Create Time   : 2020-02-25 10:28
#   Last Modified : 2020-02-25 10:28
#   Describe      :
#
# ====================================================

head = """/// generated by genInit.py
#include "EvtRecEvent/EvtRecVeeVertex.h"

#include "HadronInfo/ParticleInf.h"

#include "DCListSvc/DCListSvc.h"


void DCListSvc::init() {
    SmartDataPtr<Event::EventHeader> eventHeader(eventSvc_,
                                                 "/Event/EventHeader");
    if (m_eventID == eventHeader->eventNumber() &&
        m_runID == eventHeader->runNumber()) {
        return;
    } 
    m_runID = eventHeader->runNumber();
    m_eventID = eventHeader->eventNumber();
    /// cout << "Info in DCListSvc::init : ";
    /// cout << "#run = " << "m_runID << ", #id = " << "m_eventID << endl;
"""
decayList = [
    "m_ElectronList",
    "m_ElectronAllList",
    "m_PionPrimaryList",
    "m_PionAllList",
    "m_KaonPrimaryList",
    "m_KaonAllList",
    "m_ProtonPrimaryList",
    "m_ProtonAllList",
    "m_LambdaList",
    "m_Pi0List",
    "m_KsList",
    "m_EtaList",
    "m_PhotonList",
    "m_OmegaList",
    "m_omegaList",
    "m_XimList",
    "m_XimBarList",
    "m_Sigma0List",
    "m_Sigma0BarList",
    "m_SigmapList",
    "m_omegaList",
    "m_EtatoPiPiPi0List",
    "m_LambdaBarList",
    "m_OmegaBarList",
    "m_SigmapBarList",
    "m_Xi0List",
    "m_Xi0BarList",
    "m_PhotonList",
    "m_PhotonSoloList",
]
for d in set(decayList):
    head += "{}.eraseContents();".format(d)
    head += 'm_initList["{}"] = true;'.format(d)
head += "}"
f = open('Init.cpp', 'w')
f.write(head)
f.close()
import os
os.system("clang-format Init.cpp -i")
