/// generated by genInit.py
#include "EvtRecEvent/EvtRecVeeVertex.h"

#include "HadronInfo/ParticleInf.h"

#include "DCListSvc/DCListSvc.h"

void DCListSvc::init() {
    SmartDataPtr<Event::EventHeader> eventHeader(eventSvc_,
                                                 "/Event/EventHeader");
    if (m_eventID == eventHeader->eventNumber() &&
        m_runID == eventHeader->runNumber()) {
        return;
    }
    m_runID = eventHeader->runNumber();
    m_eventID = eventHeader->eventNumber();
    /// cout << "Info in DCListSvc::init : ";
    /// cout << "#run = " << "m_runID << ", #id = " << "m_eventID << endl;
    m_ElectronList.eraseContents();
    m_initList["m_ElectronList"] = true;
    m_ElectronAllList.eraseContents();
    m_initList["m_ElectronAllList"] = true;
    m_PionPrimaryList.eraseContents();
    m_initList["m_PionPrimaryList"] = true;
    m_PionAllList.eraseContents();
    m_initList["m_PionAllList"] = true;
    m_KaonPrimaryList.eraseContents();
    m_initList["m_KaonPrimaryList"] = true;
    m_KaonAllList.eraseContents();
    m_initList["m_KaonAllList"] = true;
    m_ProtonPrimaryList.eraseContents();
    m_initList["m_ProtonPrimaryList"] = true;
    m_ProtonAllList.eraseContents();
    m_initList["m_ProtonAllList"] = true;
    m_LambdaList.eraseContents();
    m_initList["m_LambdaList"] = true;
    m_Pi0List.eraseContents();
    m_initList["m_Pi0List"] = true;
    m_KsList.eraseContents();
    m_initList["m_KsList"] = true;
    m_EtaList.eraseContents();
    m_initList["m_EtaList"] = true;
    m_PhotonList.eraseContents();
    m_initList["m_PhotonList"] = true;
    m_OmegaList.eraseContents();
    m_initList["m_OmegaList"] = true;
    m_OmegamList.eraseContents();
    m_initList["m_OmegamList"] = true;
    m_XimList.eraseContents();
    m_initList["m_XimList"] = true;
    m_Sigma0List.eraseContents();
    m_initList["m_Sigma0List"] = true;
    m_SigmapList.eraseContents();
    m_initList["m_SigmapList"] = true;
}